server:
  port: 8889
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zhangquanli/spring-cloud-config-demo
          search-paths: config
          username:
          password:
